version: '3.8'

services:
    DockerProxmoxBackup:
        # hostname: "{{.Node.Hostname}}"
        hostname: devtools
        # image: ghcr.io/lyze237/dockerproxmoxbackup:main
        image: dockerproxmoxbackup
        build:
            context: .
        secrets:
            - proxmox_password_secret
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /var/lib/docker/volumes:/mnt/var/lib/docker/volumes:ro
        environment:
            Proxmox__PasswordFile: "/run/secrets/proxmox_password_secret"
            Proxmox__Repository: "bdd@pbs@backups.chirps.cafe:backups"
            Proxmox__Namespace: "files"
            Proxmox__Cronjob: "0 0 3 * * ?" # https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/crontrigger.html

    PostgresExample:
        image: postgres
        environment:
            POSTGRES_PASSWORD: password

    OtherPostgresExample:
        image: postgres
        labels:
            backup.name: other
        environment:
            POSTGRES_PASSWORD: password

secrets:
    proxmox_password_secret:
        file: proxmox_password.secret
